services:
  api:
    image: mepro-be
    build:
      context: .
    ports:
      - 4011:3000
    volumes:
      - './config/:/app/config/'
    networks:
      - mepro-net

networks:
  mepro-net:
      driver: bridge
