app:
  name: Me Pro
  port: 4011

db:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: mepro-dev
  synchronize: true
  logging:
    - info
    - error

oauth:
  google:
    clientID: app-id.apps.googleusercontent.com
    clientSecret: app-client-secret

jwt:
  secret: jwt-secret
  expiresIn: 2880

image:
  fallbackImageProviders:
    - s3

s3:
  region: us-east-1
  bucketName: bucket-name
  accessKeyId: access-key-id
  secretAccessKey: secret-access-key

imagekit:
  urlEndpoint: imagekit-url-endpoint
  publicKey: public_key
  privateKey: private_key

mailer:
  host: smtp.office365.com
  port: 587
  secure: false
  user: mepro@fayedark.com
  pass: secret
  from: mepro@fayedark.com
